[package]
name = "tevm-cli"
version = "0.1.0"
edition = "2021"
description = "CLI tool to run Claude Code with specified prompt"
authors = ["Tevm Team"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
